# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
title: "OCI Arcade Resource Manager Stack"
stackDescription: "Arcade"
schemaVersion: 1.1.0
version: "20200301"
locale: "en"

variableGroups:
  - title: "Hidden"
    visible: false
    variables:
    - tenancy_ocid
    - region
    - bucket_ns
    - current_user_ocid
    - compartment_ocid
    - instance_count
    - instance_state
    - cloud_agent_plugins
    - source_type
    - boot_volume_backup_policy
    - block_storage_sizes_in_gbs
    - assign_public_ip
    - public_ip
    
  - title: "General Configuration"
    visible: true
    variables:
    - git_repo
    - apigw-dn
    - enable_api_key
    
  - title: "Compute Configuration"
    visible: true  
    variables:
    - is_free_tier
    - compute_shape
    - arcade-web_source_image_id
    - custom_ssh_key
    - custom_adb_admin_password

  - title: "Kafka Configuration"
    visible: true  
    variables:
    - bootstrap_server
    - topic
    - kafka_user
    - kafka_password

variables:
  is_free_tier:
    type: boolean
    title: "ADW Free Tier"
    required: true
    default: true
    visible: true

  enable_api_key:
    type: boolean
    title: "Generate API Key"
    required: true
    default: true
    visible: true

#  arcade-web_source_image_id:
#    type: oci:core:image:id
#    dependsOn:
#      compartmentId: ${compartment_ocid}
#    required: true
#    visible: true
#    title: "Arcade Web Compute Image"

#  compute_shape:
#    type: oci:core:instanceshape:name
#    description: Select a shape
#    dependsOn:
#      compartmentId: ${compartment_ocid}
#    title: "Arcade Web Compute"
#    required: true
#    default: "VM.Standard.A1.Flex"
#    visible: true

#  region:
#    type: oci:identity:region:name
#    required: true
#    visible: true

#  compartment_ocid:
#    type: oci:identity:compartment:id
#    required: true
#    title: "Compartment"
#    visible: true

#  tenancy_ocid:
#    type: string
#    required: true
#    title: "Tenancy"
#    visible: true

  apigw-dn:
    type: string
    required: false
    title: "APIGW Domain Name"
    visible: true

#   user_id:
#    type: string
#    required: true
#    title: "User"
#    visible: true

#  custom_ssh_key:
#    type: oci:core:ssh:publickey
#    required: true
#    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
#    title: "Arcade Web Compute SSH Key"

#  bucket_ns:
#    type: string
#    required: true
#    title: "Bucket Namespace"
#    visible: true

  git_repo:
    type: string
    required: true
    title: "GIT Repository URL"
    visible: true

  custom_adb_admin_password:
    type: password
    required: true
    title: "ADW Password"

  bootstrap_server:
    type: string
    required: true
    title: "Bootstrap Server"
    visible: true

  kafka_user:
    type: string
    required: false
    title: "Kafka User"
    visible: true
    
  kafka_password:
    type: string
    required: false
    title: "Kafka Password"
    visible: true
    
  topic:
    type: string
    required: true
    title: "Topic"
    visible: true

  source_ocid:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Oracle Linux"      
      operatingSystemVersion: "8"
      shape: ${shape}

  shape:
    type: oci:core:instanceshape:name
    description: Select a shape
    dependsOn:
      compartmentId: ${compartment_ocid}
      default: "VM.Standard.A1.Flex"
                                    
  ssh_public_keys:
    type: oci:core:ssh:publickey
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"

  public_ip:
    default: "EPHEMERAL"
                                    
  instance_display_name:
    default: "F1Sim Cloud Ingestiono"

  instance_flex_memory_in_gbs:
    default: "6"

  instance_flex_ocpus:
    default: "1"

  assign_public_ip:
    default: true
